[theme]
primaryColor = "#225BFD"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202736"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
